services:
  mysql5.7:
    image: mysql:5.7.41
    environment:
      MYSQL_ROOT_PASSWORD: root123
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - mysql5.7_data:/var/lib/mysql  
      - ./mysql57/conf:/etc/mysql/conf.d

  mysql8.0:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: root123
      TZ: Asia/Shanghai
    ports:
      - 3307:3306
    volumes:
      - mysql8.0_data:/var/lib/mysql
      - ./mysql80/conf:/etc/mysql/conf.d
    command:
      - --default-authentication-plugin=mysql_native_password # 避免PHP等客户端兼容问题

  redis6.2:
    image: redis:6.2.14
    environment:
      TZ: Asia/Shanghai
    ports:
      - 6379:6379
    volumes:
      - redis6.2_data:/data  
      # - ./redis/conf/redis.conf:/etc/redis/redis.conf  # 自定义配置，默认容器内不包含配置文件，可以从http://download.redis.io下载，或者从redis压缩包中获取
                  
  frankenphp8.4:
      build: 
        context: .
        dockerfile: frankenphp/Dockerfile
      environment:
        TZ: Asia/Shanghai
      ports:
        - "80:80" # HTTP
        - "443:443" # HTTPS
      volumes:
        - ./www:/app/public
        - caddy_data:/data
        - caddy_config:/config
        # - ./frankenphp/Caddyfile:/etc/frankenphp/Caddyfile
      tty: true

volumes:
  mysql5.7_data:
  mysql8.0_data:
  redis6.2_data:
  caddy_data:
  caddy_config: