services:
  mysql57:
    image: mysql:5.7.41
    container_name: mysql57
    environment:
      MYSQL_ROOT_PASSWORD: root123
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - mysql5.7.41_data:/var/lib/mysql  
      - ./mysql57/conf:/etc/mysql/conf.d

  mysql80:
    image: mysql:8.0.35
    container_name: mysql80
    environment:
      MYSQL_ROOT_PASSWORD: root123
      TZ: Asia/Shanghai
    ports:
      - 3307:3306
    volumes:
      - mysql8.0.35_data:/var/lib/mysql
      - ./mysql80/conf:/etc/mysql/conf.d
    command:
      - --default-authentication-plugin=mysql_native_password # 避免PHP等客户端兼容问题

  redis:
    image: redis:6.2.14
    container_name: redis
    environment:
      TZ: Asia/Shanghai
    ports:
      - 6379:6379
    volumes:
      - redis6.2.14_data:/data  
      # - ./redis/conf/redis.conf:/etc/redis/redis.conf  # 自定义配置，默认容器内不包含配置文件，可以从http://download.redis.io下载，或者从redis压缩包中获取

  php73:
    build:
      context: .
      dockerfile: php73/Dockerfile
    container_name: php73
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./php73/php.ini-development:/usr/local/etc/php/php.ini
      - ./php73/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./www:/usr/share/nginx/html

  php81:
    build:
      context: .
      dockerfile: php81/Dockerfile
    container_name: php81
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./php81/php.ini-development:/usr/local/etc/php/php.ini
      - ./php81/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./www:/usr/share/nginx/html

  nginx:
    image: nginx:1.26.3
    container_name: nginx
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www:/usr/share/nginx/html
    ports:
      - 8080:80

volumes:
  mysql5.7.41_data:
  mysql8.0.35_data:
  redis6.2.14_data: